name: dotnet package

on: [push]

jobs:
  build:

    runs-on:  ubuntu-latest
    strategy:
      matrix:
      #  dotnet-version: [ '6.0.x', '7.0.x' ] # [ '3.0', '3.1.x', '5.0.x' ]
        dotnet-version: [ '6.0', '7.0' ]

    steps:
      - uses: docker://mcr.microsoft.com/dotnet/sdk:${{ matrix.dotnet-version }}
        with:
          dotnet-version: ${{ matrix.dotnet-version }}      
      - uses: actions/checkout@v3
    #  - name: Setup dotnet ${{ matrix.dotnet-version }}
     #   uses: actions/setup-dotnet@v2
     #   with:
     #     dotnet-version: ${{ matrix.dotnet-version }}
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version
      - name: Set dotnet SDK version
        run: dotnet new globaljson
      - name: build
        run: dotnet build .
      - name: test
        run: dotnet test . --no-build