name: build

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  DOTNET_VERSION: '7.0.x' # The .NET SDK version to use

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Test
      run: dotnet test --configuration Release

  deploy:
    if: github.ref == 'refs/heads/master'
    name: deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Create nuget packages
      run: |
        dotnet pack ./src/PlainML/PlainML.csproj --configuration Release --output nupkgs -p:PackageVersion=0.0.${{ github.run_number }} \
        && dotnet pack ./src/PlainML.Core/PlainML.Core.csproj --configuration Release --output nupkgs -p:PackageVersion=0.0.${{ github.run_number }} \
        && dotnet pack ./src/PlainML.Infrastructure/PlainML.Infrastructure.csproj --configuration Release --output nupkgs -p:PackageVersion=0.0.${{ github.run_number }}


    - name: Push nuget packages
      run: dotnet nuget push "nupkgs/*.nupkg" --api-key ${{secrets.nuget_api_key}} --source https://api.nuget.org/v3/index.json